import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import siteData from "../site-data.json";
import SiteApp from "./SiteApp";

afterEach(() => {
  window.history.replaceState({}, "", "/");
  vi.unstubAllGlobals();
  cleanup();
});

describe("public CoupFE-EDA site", () => {
  it("keeps the evidence-first narrative and leads with one real solver field", () => {
    const { container } = render(<SiteApp />);
    expect(screen.getByRole("heading", { level: 1, name: /EDA-aware multiphysics, from design inputs to reviewable evidence/i })).toBeInTheDocument();
    expect(screen.getAllByRole("heading", { level: 1 })).toHaveLength(1);
    expect(screen.getByRole("heading", { name: /A traceable path from design inputs to engineering evidence/i })).toBeInTheDocument();
    for (const step of [
      "Design and case inputs",
      "Identity and provenance",
      "Analysis representation",
      "Selected analysis",
      "Reviewable evidence",
      "Bounded feedback",
    ]) {
      expect(screen.getByText(step)).toBeInTheDocument();
    }

    expect(screen.getByRole("heading", { name: /A stress field generated by the package, not a concept image/i })).toBeInTheDocument();
    expect(screen.getByText(siteData.tsvField.caseId)).toBeInTheDocument();
    expect(screen.getByText(/2,400 radial nodes/i)).toBeInTheDocument();
    const video = container.querySelector("#solver-field video");
    expect(video).not.toBeNull();
    expect(video).toHaveAttribute("src", expect.stringContaining("load-sweep.webm"));
    expect(video).toHaveAttribute("poster", expect.stringContaining("contour.svg"));
    expect(video).toHaveAttribute("aria-describedby", "tsv-load-sweep-caption");
    expect(screen.getByText(siteData.tsvField.videoInterpretation)).toBeInTheDocument();
    expect(screen.getByRole("link", { name: /Open solver-derived contour/i })).toHaveAttribute("href", expect.stringContaining("contour.svg"));
    expect(screen.getByRole("link", { name: "Raw field JSON" })).toHaveAttribute("href", expect.stringContaining("field.json"));
    expect(screen.getByRole("link", { name: "SHA-256 manifest" })).toHaveAttribute("href", expect.stringContaining("visual-evidence.json"));

    expect(screen.getByText("526,338-DOF fixed-size solve")).toBeInTheDocument();
    expect(screen.getByRole("img", { name: /Median solve wall time decreases/i })).toBeInTheDocument();
    expect(screen.getByRole("heading", { name: /Checked foundations; real-device validation remains open/i })).toBeInTheDocument();
    expect(screen.getByRole("heading", { name: "3-D TSV reference case" })).toBeInTheDocument();
  }, 15_000);

  it("shows only provenance-linked CoupFE-EDA simulation media", () => {
    render(<SiteApp />);
    expect(screen.getByRole("heading", { name: /More views generated from checked CoupFE-EDA runs/i })).toBeInTheDocument();
    for (const media of siteData.simulationMedia) {
      const card = screen.getByRole("heading", { name: media.title }).closest("article");
      expect(card).not.toBeNull();
      expect(within(card!).getByRole("img", { name: media.alt })).toHaveAttribute("src", expect.stringContaining(media.asset));
      expect(within(card!).getByRole("link", { name: "Runner" })).toHaveAttribute("href", expect.stringContaining(media.runnerPath));
      expect(within(card!).getByRole("link", { name: "Oracle" })).toHaveAttribute("href", expect.stringContaining(media.resultPath));
      expect(within(card!).getByRole("link", { name: "SHA-256 record" })).toHaveAttribute("href", expect.stringContaining(media.evidencePath));
      expect(within(card!).getByText("Claim boundary")).toBeInTheDocument();
    }
    expect(screen.getByText(/not stock imagery or AI-generated concepts/i)).toBeInTheDocument();
  });

  it("groups integration demonstrations separately from real and focused verification", () => {
    render(<SiteApp />);
    const integrationGroup = screen.getByRole("heading", { name: /Design identities carried into engineering screens/i }).closest("section");
    const verificationGroup = screen.getByRole("heading", { name: /Selected physics and solver examples/i }).closest("section");
    expect(integrationGroup).not.toBeNull();
    expect(verificationGroup).not.toBeNull();

    for (const title of ["TSV-to-device screening", "Design-linked solder screening"]) {
      expect(within(integrationGroup!).getByRole("heading", { name: title })).toBeInTheDocument();
      expect(within(verificationGroup!).queryByRole("heading", { name: title })).not.toBeInTheDocument();
    }
    for (const title of ["Axisymmetric TSV stress field", "Partitioned ETV cycle", "Hex8 dissipation by layer"]) {
      expect(within(verificationGroup!).getByRole("heading", { name: title })).toBeInTheDocument();
      expect(within(integrationGroup!).queryByRole("heading", { name: title })).not.toBeInTheDocument();
    }
  });

  it("gives every displayed workflow guide, runner, retained result, and claim boundary", () => {
    render(<SiteApp />);
    const examples = document.querySelector<HTMLElement>("#examples")!;
    for (const title of [
      "Axisymmetric TSV stress field",
      "Partitioned ETV cycle",
      "Hex8 dissipation by layer",
      "Design-linked solder screening",
      "TSV-to-device screening",
    ]) {
      const card = within(examples).getByRole("heading", { name: title }).closest("article");
      expect(card).not.toBeNull();
      expect(within(card!).getByRole("link", { name: "Guide" })).toHaveAttribute("href", expect.stringContaining("github.com/tengzhang48/CoupFE-EDA/blob/main/"));
      expect(within(card!).getByRole("link", { name: "Code" })).toHaveAttribute("href", expect.stringContaining("/run.py"));
      expect(within(card!).getByRole("link", { name: "Retained result" }).getAttribute("href")).toMatch(/expected_(?:results|metrics)\.json$/);
      expect(within(card!).getByText("Claim boundary")).toBeInTheDocument();
    }
  });

  it("orders the public sections and exposes navigation and evidence destinations", () => {
    const { container } = render(<SiteApp />);
    const orderedIds = ["how-it-works", "solver-field", "simulations", "interface", "examples", "performance", "validation"];
    for (const id of orderedIds) expect(container.querySelector(`#${id}`)).not.toBeNull();
    for (let index = 0; index < orderedIds.length - 1; index += 1) {
      const current = container.querySelector(`#${orderedIds[index]}`)!;
      const next = container.querySelector(`#${orderedIds[index + 1]}`)!;
      expect(current.compareDocumentPosition(next) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();
    }

    const desktopNavigation = screen.getByRole("navigation", { name: "Project website" });
    for (const [name, href] of [
      ["How it works", "#how-it-works"],
      ["Simulations", "#simulations"],
      ["Examples", "#examples"],
      ["Evidence", "#validation"],
      ["Performance", "#performance"],
    ]) {
      expect(within(desktopNavigation).getByRole("link", { name }).getAttribute("href")).toBe(href);
    }
    const mobileNavigation = screen.getByRole("navigation", { name: "Mobile project website" });
    const mobileDetails = mobileNavigation.closest("details")!;
    mobileDetails.setAttribute("open", "");
    const mobileExamplesLink = within(mobileNavigation).getByRole("link", { name: "Examples" });
    mobileExamplesLink.addEventListener("click", (event) => event.preventDefault(), { once: true });
    fireEvent.click(mobileExamplesLink);
    expect(mobileDetails).not.toHaveAttribute("open");
    expect(screen.getByRole("navigation", { name: "Real field workbench" })).toBeInTheDocument();
    expect(screen.getByRole("navigation", { name: "Validation records" })).toBeInTheDocument();
    expect(screen.getByRole("navigation", { name: "Project resources" })).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "Skip to content" })).toHaveAttribute("href", "#main-content");
  });

  it("labels Pages as retained evidence and does not expose a fake run action", () => {
    window.history.replaceState({}, "", "/?surface=workbench");
    render(<SiteApp />);
    expect(screen.getByText(/Retained CoupFE field explorer — GitHub Pages does not run the solver/i)).toBeInTheDocument();
    expect(screen.getByRole("heading", { name: "Inspect the field behind the claim." })).toBeInTheDocument();
    expect(screen.getByRole("region", { name: "Retained solver run" })).toHaveTextContent(/cannot execute Python or CoupFE/i);
    expect(screen.queryByRole("button", { name: /run the fixed/i })).not.toBeInTheDocument();
    expect(screen.queryByRole("button", { name: /simulate/i })).not.toBeInTheDocument();
  });

  it("does not autoplay or loop solver media when reduced motion is requested", async () => {
    vi.stubGlobal("matchMedia", vi.fn().mockReturnValue({
      matches: true,
      addEventListener: vi.fn(),
      removeEventListener: vi.fn(),
    }));
    const { container } = render(<SiteApp />);
    const video = container.querySelector("#solver-field video");
    await waitFor(() => expect(video).not.toHaveAttribute("autoplay"));
    expect(video).not.toHaveAttribute("loop");
  });
});
